backend:
  name: git-gateway
  branch: main

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: content/posts
    media_folder: img
    create: true
    fields:
      - { name: type, label: Type }
      - { name: title, label: Title }
      - { name: author, label: Author }
      - { name: category, label: Category }
      - { name: date, label: Date, widget: datetime }
      - { name: slug, label: Path }
      - { name: postImage, label: Image, widget: 'image', media_folder: 'img' }
      - { name: metaDescription, label: Description }
      - { name: body, label: Body, widget: markdown }
